name:                example-project
version:             0.1.0.0
license:             BSD3
author:              "Niklas Hambüchen"
maintainer:          "mail@nh2.me"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  example-project-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example-project
